# Generated by Django 4.2.16 on 2026-04-07 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Full display name of the product.', max_length=255)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit — unique product code. Optional.', max_length=100, null=True, unique=True)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Per-unit purchase or production cost. Must be ≥ 0.', max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Per-unit retail price charged to the customer. Must be ≥ cost_price.', max_digits=12)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Current available stock units. Do NOT update this directly — it is managed automatically by sale signals.')),
                ('minimum_stock_level', models.PositiveIntegerField(default=10, help_text='When stock_quantity falls to or below this value, a low-stock alert and restock recommendation are generated.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive products are hidden from sale entry forms but are preserved for historical sales data integrity.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='The product category this item belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['product_name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='idx_products_cat_active'), models.Index(fields=['is_active', 'stock_quantity'], name='idx_products_active_stock')],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('cost_price__gte', 0)), name='chk_product_cost_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('selling_price__gte', 0)), name='chk_product_selling_price_non_negative'),
        ),
    ]
