# Generated by Django 4.2.16 on 2026-04-07 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('declining_sales', 'Declining Sales'), ('branch_underperformance', 'Branch Underperformance'), ('sales_drop', 'Abnormal Sales Drop'), ('forecast_risk', 'Forecast Risk'), ('high_demand', 'High Demand')], db_index=True, help_text='The category of condition that triggered this alert.', max_length=50)),
                ('alert_message', models.TextField(help_text='Plain-language description of the alert condition.')),
                ('priority_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], db_index=True, default='Medium', help_text='Urgency level: High (critical), Medium (warning), Low (informational).', max_length=10)),
                ('related_entity_type', models.CharField(blank=True, choices=[('product', 'Product'), ('branch', 'Branch'), ('category', 'Category'), ('customer', 'Customer'), ('overall', 'Overall Business')], help_text='Type of entity this alert is about.', max_length=20, null=True)),
                ('related_entity_id', models.IntegerField(blank=True, help_text='PK of the related entity.', null=True)),
                ('related_entity_name', models.CharField(blank=True, default='', help_text='Cached display name of the entity at alert creation time.', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False when dismissed by a user.')),
                ('dismissed_at', models.DateTimeField(blank=True, help_text='Timestamp when this alert was dismissed.', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', 'is_active'], name='idx_alert_type_active'), models.Index(fields=['priority_level', 'is_active', 'created_at'], name='idx_alert_priority_active'), models.Index(fields=['related_entity_type', 'related_entity_id'], name='idx_alert_entity')],
            },
        ),
    ]
