# Generated by Django 4.2.16 on 2026-04-07 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('branches', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of units sold. Must be greater than zero.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Actual selling price per unit at the time of this sale.', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='quantity × unit_price. Computed automatically.', max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='quantity × product.cost_price at time of sale. Computed automatically.', max_digits=14)),
                ('total_profit', models.DecimalField(decimal_places=2, help_text='total_amount − total_cost. Computed automatically.', max_digits=14)),
                ('sale_date', models.DateField(db_index=True, help_text='The calendar date when the sale took place.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(help_text='The branch where this sale occurred.', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='branches.branch')),
                ('customer', models.ForeignKey(blank=True, help_text='The purchasing customer. Null for anonymous walk-in sales.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer')),
                ('product', models.ForeignKey(help_text='The product that was sold.', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='products.product')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'sales',
                'ordering': ['-sale_date', '-created_at'],
                'indexes': [models.Index(fields=['branch', 'sale_date'], name='idx_sales_branch_date'), models.Index(fields=['product', 'sale_date'], name='idx_sales_product_date'), models.Index(fields=['customer', 'sale_date'], name='idx_sales_customer_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='chk_sale_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='chk_sale_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', 0)), name='chk_sale_total_amount_non_negative'),
        ),
    ]
