# Generated by Django 4.2.16 on 2026-04-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Customer's full display name.", max_length=255)),
                ('phone', models.CharField(blank=True, default='', help_text='Contact phone number. Optional.', max_length=30)),
                ('email', models.EmailField(blank=True, default='', help_text='Contact email address. Optional.', max_length=255)),
                ('region', models.CharField(blank=True, db_index=True, default='', help_text="Geographic sales region (e.g. 'North', 'East', 'Capital'). Used for regional analytics.", max_length=100)),
                ('customer_type', models.CharField(choices=[('Retail', 'Retail'), ('Wholesale', 'Wholesale'), ('VIP', 'VIP'), ('Corporate', 'Corporate')], db_index=True, default='Retail', help_text='Segment drives recommendation targeting and analytics grouping.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['customer_type', 'region'], name='idx_customer_type_region')],
            },
        ),
    ]
