# Generated by Django 4.2.16 on 2026-04-07 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='Required. 150 characters or fewer. Letters, digits, and @/./+/-/_ only.', max_length=150, unique=True)),
                ('email', models.EmailField(help_text='Used for notifications. Must be unique across the system.', max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('avatar_url', models.URLField(blank=True, default='', help_text='Optional link to user avatar image.', max_length=500)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('analyst', 'Analyst')], db_index=True, default='analyst', help_text='Controls which modules and actions this user can access.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivated users cannot log in. Preferred over deletion.')),
                ('is_staff', models.BooleanField(default=False, help_text='Grants access to the Django Admin panel.')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['username'],
                'indexes': [models.Index(fields=['role', 'is_active'], name='idx_users_role_active')],
            },
        ),
    ]
