"""
Recommendations Model
=====================
Automated business recommendations generated by the rule engine.

Design decisions:
  - Recommendations are never deleted — they are dismissed (is_active=False).
    This preserves the history of what insights the system generated and when.
  - related_entity_type + related_entity_id is a soft polymorphic reference.
    We avoid concrete FKs here because a recommendation may reference a product,
    branch, category, customer, or the whole business. Hard FKs would require
    four separate nullable FK columns.
  - The Priority ordering constant lets QuerySets return recommendations in a
    consistent, business-meaningful order without custom SQL.
  - dismiss() and reactivate() are model methods so the action is testable,
    reusable, and atomic without requiring view-layer logic.
  - RecommendationType covers the eight rule categories in the engine.
    Adding a new rule type requires adding it here and in the rule engine.
"""
from django.db import models
from django.utils import timezone


# ---------------------------------------------------------------------------
# QuerySet
# ---------------------------------------------------------------------------

class RecommendationQuerySet(models.QuerySet):

    def active(self):
        """Non-dismissed recommendations."""
        return self.filter(is_active=True)

    def dismissed(self):
        return self.filter(is_active=False)

    def high_priority(self):
        return self.filter(priority_level=Recommendation.Priority.HIGH)

    def medium_priority(self):
        return self.filter(priority_level=Recommendation.Priority.MEDIUM)

    def low_priority(self):
        return self.filter(priority_level=Recommendation.Priority.LOW)

    def by_type(self, recommendation_type):
        return self.filter(recommendation_type=recommendation_type)

    def for_entity(self, entity_type, entity_id=None):
        qs = self.filter(related_entity_type=entity_type)
        if entity_id is not None:
            qs = qs.filter(related_entity_id=entity_id)
        return qs

    def for_product(self, product_id):
        return self.for_entity(Recommendation.EntityType.PRODUCT, product_id)

    def for_branch(self, branch_id):
        return self.for_entity(Recommendation.EntityType.BRANCH, branch_id)

    def for_category(self, category_id):
        return self.for_entity(Recommendation.EntityType.CATEGORY, category_id)

    def priority_ordered(self):
        """
        Order by priority descending (High → Medium → Low), then newest first.
        Uses a CASE expression via annotate for DB-level sorting.
        """
        return self.annotate(
            priority_order=models.Case(
                models.When(priority_level=Recommendation.Priority.HIGH,   then=models.Value(1)),
                models.When(priority_level=Recommendation.Priority.MEDIUM, then=models.Value(2)),
                models.When(priority_level=Recommendation.Priority.LOW,    then=models.Value(3)),
                default=models.Value(4),
                output_field=models.IntegerField(),
            )
        ).order_by("priority_order", "-generated_at")


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

class Recommendation(models.Model):
    """
    A single business recommendation generated by the rule engine.

    Lifecycle:
        1. Rule engine evaluates conditions on current analytics data.
        2. If a condition is met and no identical active recommendation exists,
           a new Recommendation is created with is_active=True.
        3. User reads the recommendation on the dashboard or Recommendations page.
        4. User dismisses it → is_active=False. It is still stored for history.
        5. On next engine run, the condition is re-evaluated.
           If still true, a new recommendation is created.

    Recommendation types map to specific rule modules in the engine:
        restock            → stock_rules.check_low_stock()
        declining_sales    → sales_rules.check_declining_products()
        branch_performance → branch_rules.check_underperforming_branches()
        category_promotion → sales_rules.check_high_performers()
        customer_retention → customer_rules.check_inactive_vip_customers()
        forecast_risk      → sales_rules.check_forecast_risks()
        high_performer     → sales_rules.check_high_performers()
        cost_optimization  → (future expansion)
    """

    class RecommendationType(models.TextChoices):
        RESTOCK             = "restock",             "Restock Product"
        DECLINING_SALES     = "declining_sales",     "Declining Sales"
        BRANCH_PERFORMANCE  = "branch_performance",  "Branch Performance"
        CATEGORY_PROMOTION  = "category_promotion",  "Category Promotion"
        CUSTOMER_RETENTION  = "customer_retention",  "Customer Retention"
        FORECAST_RISK       = "forecast_risk",       "Forecast Risk"
        HIGH_PERFORMER      = "high_performer",      "High Performer"
        COST_OPTIMIZATION   = "cost_optimization",   "Cost Optimization"

    class EntityType(models.TextChoices):
        PRODUCT  = "product",  "Product"
        BRANCH   = "branch",   "Branch"
        CATEGORY = "category", "Category"
        CUSTOMER = "customer", "Customer"
        OVERALL  = "overall",  "Overall Business"

    class Priority(models.TextChoices):
        HIGH   = "High",   "High"
        MEDIUM = "Medium", "Medium"
        LOW    = "Low",    "Low"

    # ------------------------------------------------------------------
    # Content
    # ------------------------------------------------------------------
    recommendation_text = models.TextField(
        help_text="Plain-language description of the recommended action.",
    )
    recommendation_type = models.CharField(
        max_length=50,
        choices=RecommendationType.choices,
        db_index=True,
        help_text="The business rule category that generated this recommendation.",
    )

    # ------------------------------------------------------------------
    # Target entity (soft polymorphic reference)
    # ------------------------------------------------------------------
    related_entity_type = models.CharField(
        max_length=20,
        choices=EntityType.choices,
        null=True,
        blank=True,
        help_text="Type of business entity this recommendation is about.",
    )
    related_entity_id = models.IntegerField(
        null=True,
        blank=True,
        help_text="PK of the related entity. Null for 'overall' recommendations.",
    )
    related_entity_name = models.CharField(
        max_length=255,
        blank=True,
        default="",
        help_text="Cached display name of the entity at time of generation. Avoids extra lookups.",
    )

    # ------------------------------------------------------------------
    # Priority and lifecycle
    # ------------------------------------------------------------------
    priority_level = models.CharField(
        max_length=10,
        choices=Priority.choices,
        default=Priority.MEDIUM,
        db_index=True,
        help_text="Business urgency: High (immediate action), Medium (soon), Low (informational).",
    )
    generated_at = models.DateTimeField(
        default=timezone.now,
        db_index=True,
        help_text="When this recommendation was generated by the rule engine.",
    )
    is_active = models.BooleanField(
        default=True,
        db_index=True,
        help_text="False when dismissed by a user. Dismissed recommendations are kept for history.",
    )
    dismissed_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="Timestamp when a user dismissed this recommendation.",
    )

    objects = RecommendationQuerySet.as_manager()

    class Meta:
        db_table         = "recommendations"
        verbose_name     = "Recommendation"
        verbose_name_plural = "Recommendations"
        ordering         = ["-generated_at"]
        indexes = [
            models.Index(
                fields=["priority_level", "is_active", "generated_at"],
                name="idx_rec_priority_active",
            ),
            models.Index(
                fields=["related_entity_type", "related_entity_id"],
                name="idx_rec_entity",
            ),
        ]

    # ------------------------------------------------------------------
    # String representation
    # ------------------------------------------------------------------
    def __str__(self):
        text_preview = self.recommendation_text[:70]
        if len(self.recommendation_text) > 70:
            text_preview += "…"
        return f"[{self.priority_level}] {text_preview}"

    def __repr__(self):
        return (
            f"<Recommendation id={self.pk} type={self.recommendation_type!r} "
            f"priority={self.priority_level!r} active={self.is_active}>"
        )

    # ------------------------------------------------------------------
    # Actions
    # ------------------------------------------------------------------
    def dismiss(self):
        """Mark this recommendation as dismissed. Preserves the record."""
        if self.is_active:
            self.is_active    = False
            self.dismissed_at = timezone.now()
            self.save(update_fields=["is_active", "dismissed_at"])

    def reactivate(self):
        """Re-activate a dismissed recommendation."""
        if not self.is_active:
            self.is_active    = True
            self.dismissed_at = None
            self.save(update_fields=["is_active", "dismissed_at"])

    # ------------------------------------------------------------------
    # Computed properties
    # ------------------------------------------------------------------
    @property
    def is_high_priority(self):
        return self.priority_level == self.Priority.HIGH

    @property
    def priority_color(self):
        """CSS colour token for the priority badge. Consumed by the frontend."""
        colors = {
            self.Priority.HIGH:   "red",
            self.Priority.MEDIUM: "amber",
            self.Priority.LOW:    "green",
        }
        return colors.get(self.priority_level, "gray")

    @property
    def type_icon(self):
        """Icon name hint for the frontend (Lucide React icon names)."""
        icons = {
            self.RecommendationType.RESTOCK:            "package",
            self.RecommendationType.DECLINING_SALES:    "trending-down",
            self.RecommendationType.BRANCH_PERFORMANCE: "building-2",
            self.RecommendationType.CATEGORY_PROMOTION: "tag",
            self.RecommendationType.CUSTOMER_RETENTION: "users",
            self.RecommendationType.FORECAST_RISK:      "alert-triangle",
            self.RecommendationType.HIGH_PERFORMER:     "trending-up",
            self.RecommendationType.COST_OPTIMIZATION:  "dollar-sign",
        }
        return icons.get(self.recommendation_type, "info")
