# Generated by Django 4.2.16 on 2026-04-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_target_type', models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('branch', 'Branch'), ('overall', 'Overall Business')], db_index=True, help_text='The type of entity being forecast.', max_length=20)),
                ('target_id', models.IntegerField(blank=True, db_index=True, help_text="PK of the target entity. Null for 'overall' forecasts.", null=True)),
                ('forecast_period_months', models.IntegerField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months')], help_text='Number of months ahead to forecast: 1, 3, or 6.')),
                ('model_name', models.CharField(choices=[('moving_average', 'Moving Average'), ('linear_regression', 'Linear Regression'), ('random_forest', 'Random Forest')], help_text='The statistical or ML model used to generate this forecast.', max_length=30)),
                ('predicted_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Total predicted units over the forecast period.', max_digits=14, null=True)),
                ('predicted_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Total predicted revenue over the forecast period.', max_digits=14, null=True)),
                ('mae', models.DecimalField(blank=True, decimal_places=4, help_text='Mean Absolute Error — average magnitude of prediction errors.', max_digits=10, null=True)),
                ('rmse', models.DecimalField(blank=True, decimal_places=4, help_text='Root Mean Squared Error — penalises large errors more than MAE.', max_digits=10, null=True)),
                ('commentary', models.TextField(blank=True, default='', help_text='Auto-generated plain-language interpretation of the forecast.')),
                ('forecast_data', models.JSONField(default=list, help_text='Array of {period, actual, predicted} dicts covering both historical and forecast months.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Forecast',
                'verbose_name_plural': 'Forecasts',
                'db_table': 'forecasts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['forecast_target_type', 'target_id', 'created_at'], name='idx_forecast_target_created')],
            },
        ),
        migrations.AddConstraint(
            model_name='forecast',
            constraint=models.CheckConstraint(check=models.Q(('forecast_period_months__in', [1, 3, 6])), name='chk_forecast_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='forecast',
            constraint=models.CheckConstraint(check=models.Q(('mae__isnull', True), ('mae__gte', 0), _connector='OR'), name='chk_forecast_mae_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='forecast',
            constraint=models.CheckConstraint(check=models.Q(('rmse__isnull', True), ('rmse__gte', 0), _connector='OR'), name='chk_forecast_rmse_non_negative'),
        ),
    ]
