# Generated by Django 4.2.16 on 2026-04-07 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_text', models.TextField(help_text='Plain-language description of the recommended action.')),
                ('recommendation_type', models.CharField(choices=[('restock', 'Restock Product'), ('declining_sales', 'Declining Sales'), ('branch_performance', 'Branch Performance'), ('category_promotion', 'Category Promotion'), ('customer_retention', 'Customer Retention'), ('forecast_risk', 'Forecast Risk'), ('high_performer', 'High Performer'), ('cost_optimization', 'Cost Optimization')], db_index=True, help_text='The business rule category that generated this recommendation.', max_length=50)),
                ('related_entity_type', models.CharField(blank=True, choices=[('product', 'Product'), ('branch', 'Branch'), ('category', 'Category'), ('customer', 'Customer'), ('overall', 'Overall Business')], help_text='Type of business entity this recommendation is about.', max_length=20, null=True)),
                ('related_entity_id', models.IntegerField(blank=True, help_text="PK of the related entity. Null for 'overall' recommendations.", null=True)),
                ('related_entity_name', models.CharField(blank=True, default='', help_text='Cached display name of the entity at time of generation. Avoids extra lookups.', max_length=255)),
                ('priority_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], db_index=True, default='Medium', help_text='Business urgency: High (immediate action), Medium (soon), Low (informational).', max_length=10)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this recommendation was generated by the rule engine.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False when dismissed by a user. Dismissed recommendations are kept for history.')),
                ('dismissed_at', models.DateTimeField(blank=True, help_text='Timestamp when a user dismissed this recommendation.', null=True)),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'db_table': 'recommendations',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['priority_level', 'is_active', 'generated_at'], name='idx_rec_priority_active'), models.Index(fields=['related_entity_type', 'related_entity_id'], name='idx_rec_entity')],
            },
        ),
    ]
