# Generated by Django 4.2.16 on 2026-04-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(help_text='Unique display name for this branch. Used as a label in analytics charts.', max_length=255, unique=True)),
                ('location', models.CharField(blank=True, default='', help_text='Physical address or city of this branch.', max_length=255)),
                ('manager_name', models.CharField(blank=True, default='', help_text='Name of the branch manager. Informational only.', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive branches are hidden from sale entry but retained for historical data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'db_table': 'branches',
                'ordering': ['branch_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('branch_name',), name='uniq_branch_name'),
        ),
    ]
